[package]
name = "docker_notif"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "*"
tokio = { version = "1", features = ["full"] }
serde_json = { version = "1.0.151" }
serde = { version = "1.0.229" }
anyhow = { version = "1.0.104" }
oci-distribution = { version = "0.11.0", default-features = false, features = [
  "rustls-tls",
] }
oci-client = { version = "0.17.0", default-features = false, features = [
  "rustls-tls",
] }
discord-webhook2 = { version = "0.4.3", default-features = false, features = [
  "rustls-tls",
] }
tokio-cron-scheduler = "0.15.1"
serde-saphyr = "1.2.0"
chrono-tz = "0.10.4"
chrono = "0.4.45"
