[package]
name = "docker_notif"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "*"
tokio = { version = "1", features = ["full"] }
serde_json = { version = "1.0.151" }
serde = { version = "1.0.229" }
anyhow = { version = "1.0.104" }
dotenvy = "0.15.7"
oci-distribution = "0.11.0"
oci-client = "0.17.0"
webhook = "2.1.2"
tokio-cron-scheduler = "0.15.1"
serde-saphyr = "1.2.0"
chrono-tz = "0.10.4"
chrono = "0.4.45"
